tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "antigen"
brew "genact"
brew "git"
brew "xz"
brew "python"
brew "mackup"
brew "mas"
brew "python@2"
brew "repo"
brew "vim"
brew "wget"
brew "zsh"
cask "alfred"
cask "android-studio"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "licecap"
cask "pdf-expert"
cask "proxifier"
cask "shadowsocksx-ng"
cask "snipaste"
cask "sourcetree"
cask "sublime-text"
cask "the-unarchiver"
cask "thunder"
cask "visual-studio-code"
mas "MindNode", id: 1289197285
mas "Speedtest", id: 1153157709
mas "微信", id: 836500024
